apiVersion: skaffold/v4beta5
kind: Config
metadata:
  name: raisehand
deploy:
  kubectl:
    defaultNamespace: raisehand
build:
  local:
    push: false
  artifacts:
    - image: gupta840/raisehand-compilers
      context: compilers
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: gupta840/raisehand-questions
      context: questions
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.js"
            dest: .
manifests:
  rawYaml:
    - ./infra/k8s/*
    - ./infra/k8s-dev/*
