# https://cert-manager.io/docs/reference/api-docs/#cert-manager.io/v1.Certificate
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: raisehand-software-tls
spec:
  secretName: raisehand-software
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: raisehand.software
  dnsNames:
    - raisehand.software
    - www.raisehand.software
  acme:
    config:
      -http01:
        ingressClass: nginx
      domains:
        - raisehand.software
        - www.raisehand.software
