name: deploy-compilers

on:
  push:
    branches:
      - master
    paths:
      - 'compilers/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run:  cd compilers && docker build -t gupta840/raisehand-compilers .
      - run:  docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME:  ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD:  ${{ secrets.DOCKER_PASSWORD }}
      - run:  docker push gupta840/raisehand-compilers
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITAL_OCEAN_ACCESS_TOKEN }}
      - run:  doctl kubernetes cluster kubeconfig save raisehand-k8s
      - run:  kubectl rollout restart deployment compilers-depl
